const EXPIRE_TIME_GET_NEXT_A_DROP_OF_WATER = 5 * 60
const EXPIRE_TIME_TO_GET_NEXT_USER_ENERGY = 3 * 60
const EXPIRE_TIME_TO_MAX_NEXT_USER_ENERGY = 3 * 60
const MAX_WATERING_CAN = 20
const MAX_USER_ENERGY = 50