apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ts-nakama-game-demo.fullname" . }}
  labels:
    {{- include "ts-nakama-game-demo.labels" . | nindent 4 }}
automountServiceAccountToken: false
